close all
time=out.simout.Time;
areas=out.simout.Data(:,1:45);
figure('Name','Area Gas Pollutions','NumberTitle','off');
subplot(3,3,1); plot(time,areas(:,1));
xlabel("Area 1");
subplot(3,3,2); plot(time,areas(:,2));
xlabel("Area 2");
subplot(3,3,3); plot(time,areas(:,3));
xlabel("Area 3");
subplot(3,3,4); plot(time,areas(:,4));
xlabel("Area 4");
subplot(3,3,5); plot(time,areas(:,5));
xlabel("Area 5");
subplot(3,3,6); plot(time,areas(:,6));
xlabel("Area 6");
subplot(3,3,7); plot(time,areas(:,7));
xlabel("Area 7");
subplot(3,3,8); plot(time,areas(:,8));
xlabel("Area 8");
subplot(3,3,9); plot(time,areas(:,9));
xlabel("Area 9");
% text('Area Pollutions');


figure('Name','Area Noise Pollutions','NumberTitle','off');
subplot(3,3,1); plot(time,areas(:,10));
xlabel("Time");
ylabel("Area 1");
subplot(3,3,2); plot(time,areas(:,11));
xlabel("Time");
ylabel("Area 2");
subplot(3,3,3); plot(time,areas(:,12));
xlabel("Time");
ylabel("Area 3");
subplot(3,3,4); plot(time,areas(:,13));
xlabel("Time");
ylabel("Area 4");
subplot(3,3,5); plot(time,areas(:,14));
xlabel("Time");
ylabel("Area 5");
subplot(3,3,6); plot(time,areas(:,15));
xlabel("Time");
ylabel("Area 6");
subplot(3,3,7); plot(time,areas(:,16));
xlabel("Time");
ylabel("Area 7");
subplot(3,3,8); plot(time,areas(:,17));
xlabel("Time");
ylabel("Area 8");
subplot(3,3,9); plot(time,areas(:,18));
xlabel("Time");
ylabel("Area 9");

cars=out.simout.Data(:,46:end);
dataLength=size(cars);
dataLength=dataLength(1);
numCars=3;

car1=cars(:,(1:numCars:end) );
car2=cars(:,(2:numCars:end) );
car3=cars(:,(3:numCars:end) );
% dim=size(cars);
% car1=carMatrix(1,:,:);
% car2=cars(19:end,:);
% cars=reshape(cars,18,length(cars)/18)';
loc1=car1(:,[7,8]);
loc2=car2(:,[7,8]);
loc3=car3(:,[7,8]);

figure('Name','Car Positions','NumberTitle','off');
subplot(3,3,1); plot(loc1(:,1),loc1(:,2));
xlabel("car1 locations in X direction");
ylabel("car1 locations in Y direction");
subplot(3,3,2); plot(loc2(:,1),loc2(:,2));
xlabel("car2 locations in X direction");
ylabel("car2 locations in Y direction");
subplot(3,3,3); plot(loc3(:,1),loc3(:,2));
xlabel("car3 locations in X direction");
ylabel("car3 locations in Y direction");

subplot(3,3,4); plot(time,car1(:,11));
xlabel("Time");
ylabel("Areas that car1 passes by");
subplot(3,3,5); plot(time,car2(:,11));
xlabel("Time");
ylabel("Areas that car2 passes by");
subplot(3,3,6); plot(time,car3(:,11));
xlabel("Time");
ylabel("Areas that car3 passes by");
subplot(3,3,7); plot(time,car1(:,2).*car1(:,12));
xlabel("Time");
ylabel("Pollution per sec for car1");
subplot(3,3,8); plot(time,car2(:,2).*car2(:,12));
xlabel("Time");
ylabel("Pollution per sec for car2");
subplot(3,3,9); plot(time,car3(:,2).*car3(:,12));
xlabel("Time");
ylabel("Pollution per sec for car3");
